language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - LARAVEL_VERSION=5.5.*
    - LARAVEL_VERSION=5.6.*
    - LARAVEL_VERSION=5.7.*
    - LARAVEL_VERSION=5.8.*
    - LARAVEL_VERSION=^6.0

install:
    - composer require laravel/laravel:${LARAVEL_VERSION}


script:
    - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
